apiVersion: v1
kind: Service       # 对象类型为Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql     # Pod间通信的端口名称
      port: 3306        # Pod间通信的端口号
  selector:
    app: mysql        # 选择标签为app:mysql的Pod
  clusterIP: None     # 必须设置为None，表示Headless Service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: redis                             # headless service的名称
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql
          name: mid-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts: # Pod挂载的存储
            - name: data
              mountPath: /var/lib/mysql     # 将容器的/data目录挂载出来
            - name: data
              mountPath: /logs     # 将容器的/data目录挂载出来
      imagePullSecrets:
        - name: default-secret
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 5Gi
        storageClassName: csi-nas                   # 持久化存储的类型
