apiVersion: v1
kind: Service       # 对象类型为Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql     # Pod间通信的端口名称
      port: 3306        # Pod间通信的端口号
  selector:
    app: mysql        # 选择标签为app:mysql的Pod
  clusterIP: None     # 必须设置为None，表示Headless Service
