apiVersion: v1
kind: Service       # 对象类型为Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: rabbitmq     # Pod间通信的端口名称
      port: 5672       # Pod间通信的端口号
    - name: rabbitmq-mag     # Pod间通信的端口名称
      port: 15672        # Pod间通信的端口号
  selector:
    app: rabbitmq        # 选择标签为app:rabbitmq的Pod
  clusterIP: None     # 必须设置为None，表示Headless Service
