apiVersion: v1
kind: Service       # 对象类型为Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - name: redis     # Pod间通信的端口名称
      port: 6379        # Pod间通信的端口号
  selector:
    app: redis        # 选择标签为app:redis的Pod
  clusterIP: None     # 必须设置为None，表示Headless Service
