# 部署模板
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{deployment-name}}
  namespace: kms-v2
spec:
  selector:
    matchLabels:
      app: {{container-name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{container-name}}
    spec:
      containers:
        - name: {{container-name}}
          image: {{image}}
          ports:
            - containerPort: 80