# configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: devops
data:
  elasticsearch.yml: |
    cluster.name: my-es-cluster
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    discovery.seed_hosts: elasticsearch-0.devops,elasticsearch-1.devops,elasticsearch-2.devops
    cluster.initial_master_nodes: elasticsearch-0,elasticsearch-1,elasticsearch-2
    xpack.security.enabled: false
    
    # 单节点ssl证书生成后才能添加的环境变量
#    xpack.security.transport.ssl.enabled: true
#    xpack.security.transport.ssl.verification_mode: certificate
#    xpack.security.transport.ssl.client_authentication: required
#    xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
#    xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
#    xpack.security.transport.ssl.keystore.secure_password: ${SECURE_PASSWORD}
#    xpack.security.transport.ssl.truststore.secure_password: ${SECURE_PASSWORD}

#    xpack.security.http.ssl.enabled: true
#    xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
#    xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.p12

---
# es-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      protocol: TCP
    - name: transport
      port: 9300
      protocol: TCP
  type: ClusterIP

---
# es-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: devops
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: es-sa
      containers:
        - name: elasticsearch
          image: elasticsearch:8.6.2
#          command: ["/bin/bash", "-c", "sleep 600s && /usr/local/bin/docker-entrypoint.sh"] # 调试模式,启动之前先sleep 600s,可以进入容器查询对应的状态
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "0.5Gi"
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms500m -Xmx500m"
            - name: SECURE_PASSWORD
              value: NRAQ1234!
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts: # Pod挂载的存储
            - name: data
              mountPath: /usr/share/elasticsearch/data     # 将容器的/xxx/data目录挂载出来
#            - name: certs-volume
#              mountPath: /usr/share/elasticsearch/config/certs
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      imagePullSecrets:
        - name: default-secret
      volumes:
#        - name: certs-volume
#          secret:
#            secretName: elasticsearch-certs
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
            items:
              - key: elasticsearch.yml # 配合上面的配置文件挂载
                path: elasticsearch.yml
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-nas                   # 持久化存储的类型
        accessModes:
          - ReadWriteMany
