apiVersion: v1
kind: Namespace
metadata:
  name: kms-v2
---
apiVersion: v1
kind: Service
metadata:
  name: { container-name }
  namespace: kms-v2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: { container-name }
---
apiVersion: v1
kind: Deployment
metadata:
  name: { deployment-name }
  namespace: kms-v2
spec:
  selector:
    matchLabels:
      app: { deployment-name }
  replicas: 2 # 副本数量
  template:
    metadata:
      labels: # 为pod打标签,方便筛选
        app: { deployment-name } # app名称
        env: { env } # 属于哪个环境 dev/test/pre/pro
    spec:
      containers:
        - name: { container-name }
          image: { image-name }
          command: [ "./access" ]
          args: [ "-f","/app/etc/access.${ENV}.yaml" ]
          # 启动参数,可以使用环境变量,也可以使用shell ==> args: ["-c", "while true; do echo hello; sleep 10;done"]
          ports:
            - containerPort: 80
      restartPolicy: Always
