# redis部署清单
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kms-v2
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 80
      restartPolicy: Always